"""DB enum'lari (docs/DATABASE.md bolum 2). Deger = isim; PostgreSQL native enum olarak saklanir."""

from enum import StrEnum


class UserRole(StrEnum):
    REPORTER = "REPORTER"
    STAFF = "STAFF"
    MANAGER = "MANAGER"
    ADMIN = "ADMIN"


class ReporterKind(StrEnum):
    STUDENT = "STUDENT"
    ACADEMIC = "ACADEMIC"
    PERSONNEL = "PERSONNEL"


class LocationKind(StrEnum):
    CAMPUS = "CAMPUS"
    BUILDING = "BUILDING"
    FLOOR = "FLOOR"
    ROOM = "ROOM"
    WC = "WC"
    CORRIDOR = "CORRIDOR"
    OUTDOOR = "OUTDOOR"
    OTHER = "OTHER"


class CaseCategory(StrEnum):
    CLEANING = "CLEANING"
    CONSUMABLE = "CONSUMABLE"
    TECHNICAL = "TECHNICAL"
    IT = "IT"
    INFRASTRUCTURE = "INFRASTRUCTURE"
    SECURITY = "SECURITY"
    FOOD_SERVICE = "FOOD_SERVICE"
    OTHER = "OTHER"


class Priority(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class CaseStatus(StrEnum):
    # Gecis kurallari: docs/WORKFLOW.md bolum 1
    NEW = "NEW"
    ANALYZING = "ANALYZING"
    NEEDS_INFO = "NEEDS_INFO"
    CLASSIFIED = "CLASSIFIED"
    ASSIGNED = "ASSIGNED"
    ACCEPTED = "ACCEPTED"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    VERIFICATION = "VERIFICATION"
    CLOSED = "CLOSED"
    REOPENED = "REOPENED"
    ESCALATED = "ESCALATED"
    REJECTED = "REJECTED"
    MERGED = "MERGED"


class ActorType(StrEnum):
    USER = "USER"
    AGENT = "AGENT"
    SYSTEM = "SYSTEM"


class CaseEventType(StrEnum):
    # docs/WORKFLOW.md bolum 3. DB'de varchar: yeni olay tipi migration gerektirmez
    CASE_CREATED = "CASE_CREATED"
    ANALYSIS_STARTED = "ANALYSIS_STARTED"
    AI_CLASSIFIED = "AI_CLASSIFIED"
    DUPLICATE_CHECKED = "DUPLICATE_CHECKED"
    VERIFICATION_SCORED = "VERIFICATION_SCORED"
    PRIORITY_CALCULATED = "PRIORITY_CALCULATED"
    ROUTED = "ROUTED"
    SUPERVISOR_DECIDED = "SUPERVISOR_DECIDED"
    HUMAN_REVIEW_REQUESTED = "HUMAN_REVIEW_REQUESTED"
    INFO_REQUESTED = "INFO_REQUESTED"
    INFO_PROVIDED = "INFO_PROVIDED"
    CASE_MERGED = "CASE_MERGED"
    TASK_CREATED = "TASK_CREATED"
    TASK_ACCEPTED = "TASK_ACCEPTED"
    TASK_DECLINED = "TASK_DECLINED"
    TASK_REASSIGNED = "TASK_REASSIGNED"
    WORK_STARTED = "WORK_STARTED"
    WORK_COMPLETED = "WORK_COMPLETED"
    EVIDENCE_UPLOADED = "EVIDENCE_UPLOADED"
    RESOLUTION_EVALUATED = "RESOLUTION_EVALUATED"
    RESOLUTION_VERIFIED = "RESOLUTION_VERIFIED"
    CASE_CLOSED = "CASE_CLOSED"
    CASE_REOPENED = "CASE_REOPENED"
    CASE_REJECTED = "CASE_REJECTED"
    SLA_WARNING = "SLA_WARNING"
    SLA_BREACHED = "SLA_BREACHED"
    ESCALATED = "ESCALATED"
    DECISION_OVERRIDDEN = "DECISION_OVERRIDDEN"
    COMMENT_ADDED = "COMMENT_ADDED"
    FEEDBACK_SUBMITTED = "FEEDBACK_SUBMITTED"


class AttachmentKind(StrEnum):
    # REPORT: bildirim yapanin fotografi; EVIDENCE: personelin is bitti kaniti
    REPORT = "REPORT"
    EVIDENCE = "EVIDENCE"
